aidenybai/react-scan

src/core/index.ts

First, love the package 🤗  great stuff y'all. 
As I was getting this setup for some Remix apps in a monorepo I wanted to pull a hook out into a custom library. These would be useful to expose for TypeScript consumers (easy win). 
- https://github.com/aidenybai/react-scan/issues/30
- https://github.com/aidenybai/react-scan/issues/26
```tsx
import { useEffect } from 'react';
import type { Options } from 'react-scan';
export const useReactScan = (options: Options) => {
useEffect(() => {
if (typeof document === 'undefined') return;
import('react-scan').then(({ scan }) => {
scan(options);
});
}, []);
};
```

export the "Options" interface

---

src/core/web/toolbar.ts

Fix the issue [#41](https://github.com/aidenybai/react-scan/issues/41) and duplicate [#42](https://github.com/aidenybai/react-scan/issues/42)  
Bug the styles of **react-scan** `scroll-bar` styles redefines normal styles of `scroll-bar` in projects that uses **react-scan**
Issue is due to define **react-scan** `scroll-bar` global styles in file `src/core/web/toolbar`, so the solution is to define those styles of the `scroll-bar` to target the local `<div>` with id `#react-scan-toolbar`  
You can see in the picture below that the the `scroll-bar` of my project is normal and the `scroll-bar` of **react-scan** still well.

Fix #41 issue and #42(duplicate of #41), scroll-bar global styles.

---

src/cli.mts

- Replaced `NodeJS.Timeout` with `NodeJS.Timer` to handle both `setTimeout()` and `setInterval()` correctly.
- This change resolves type errors and ensures compatibility with both one-time and recurring timers.

fix: resolve TypeScript issue with interval type

---

src/core/web/toolbar.ts

Problem
Quickly dragging the toolbar can move it outside the screen area.
Adjust
- Extract boundary calculations to improve readability
- Use position delta to determine updates
Now you can freely drag the toolbar without worrying about it going out of sight.

refactor(core): simplify toolbar bounds checking logic

---

.gitignore
packages/scan/package.json
packages/scan/src/core/monitor/params/astro/Monitoring.astro
packages/scan/src/core/monitor/params/astro/component.ts
packages/scan/src/core/monitor/params/astro/index.ts
packages/scan/tsup.config.ts

Add monitoring support for astro, usage:
```
// Layout.astro
---
import Monitoring from 'react-scan/monitoring/astro'
---
<Monitoring apiKey="" url="https://monitoring.react-scan.com/api/v1/ingest"/>
```

feat(scan): add Astro monitoring component

---

packages/scan/src/core/index.ts
packages/scan/src/core/instrumentation.ts

Previously, there was no way to mount the toolbar while having the scanning turned off. Now, providing the config below will allow users to have scanning turned off by default, but still have the toolbar mounted, acting as an opt-in with the toolbar.
```typescript
scan({
enabled: false,
showToolbar: true
});
```

feat(scan): allow users to have toolbar mounted while enabled as false

---

.eslintrc.js
packages/scan/package.json
packages/scan/src/core/fast-serialize.test.ts
packages/scan/src/core/index.ts
packages/scan/src/core/instrumentation.ts
packages/scan/src/core/web/inspect-element/utils.ts
packages/scan/src/core/web/overlay.ts
packages/scan/src/core/web/utils/outline.ts
packages/scan/tsup.config.ts
packages/scan/vite.config.mts
pnpm-lock.yaml

Summary:
- use IntersectionObserver over getClientBoundingRect to minimize reflows
- optimize fast serialize
- sample renders to run isRenderUnncessaryOn
- dont merge outlines when there are significant active outlines
- flush async instead of in hot path/ avoid promise creation every render
- dont draw outlines that are out of viewport

chore(scan): optimize perf of core scan

---

packages/scan/src/core/index.ts
packages/scan/src/core/web/utils/outline.ts

Adds a check to confirm the stateNode we are scheduling is an `Element`
closes #171

fix(scan): skip renders from host components that are not Elements

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/index.jsx
packages/kitchen-sink/vite.config.mjs
pnpm-lock.yaml

* bump `react` and `react-dom` from the RC version to the official `19.0.0` release
* remove unused `babel-plugin-react-compiler` dependency
* move `vite` related dependencies into `devDependencies`
* fix a tiny bug where adding two of the same text items in the list would result in a key error 
* prevent adding an item to the list with the enter key if it's text is blank
https://github.com/user-attachments/assets/9ccb203b-cc12-43bb-bf69-efcf013689d6

chore(kitchen-sink): update dependencies and fix a key issue in the todo list

---

packages/scan/src/core/index.ts
packages/scan/src/web/assets/css/styles.tailwind.css
packages/scan/src/web/toolbar.tsx

- Remove redundant DOM nesting in shadow root
- Move container ID assignment to createToolbar
- Fix fragment elements order for better initialization

fix: move toolbar root container to createToolbar

---

packages/scan/src/web/components/inspector/overlay/index.tsx
packages/scan/src/web/components/widget/index.tsx

To fix #190 
- enforcing `ltr` on the widget so the layout stays the same in `rtl`
- enforcing `ltr` on the canvas so the text doesn't go out of the pill in `rtl`
- align the widget with the inline direction using `place-self`
some known limitations
- safari doesn't support [place-self](https://developer.mozilla.org/en-US/docs/Web/CSS/place-self#browser_compatibility) or [justify-self](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self#browser_compatibility) yet
- it doesn't fix the issue where the rect in canvas shifts slightly to the left in `rtl` (as seen in the videos below when it highlights an element). I don't have a good solution to this yet, I believe it is the scrollbar width
**Before**
https://github.com/user-attachments/assets/6b1ce4a0-5604-475e-899a-fe8126f523bc …

fix: toolbar position issue when the direction is rtl

---

BROWSER_EXTENSION_GUIDE.md
README.md

Closes #210.
This makes the browser extension guide filename a little less confusing, and updates the README with the current status of the browser extension.

Browser extension guide improvements

---

packages/scan/src/web/components/slider/index.tsx
packages/scan/src/web/views/inspector/components-tree/index.tsx
packages/scan/src/web/views/inspector/overlay/index.tsx
packages/scan/src/web/widget/index.tsx
packages/scan/src/web/widget/resize-handle.tsx

This pull request refactors the toolbar's drag and drop functionality by replacing mouse events with pointer events. This change is primarily focused on improving the drag and drop behavior on mobile devices, where pointer events provide better support for touch interactions.
- Replaced `mousedown`, `mousemove`, and `mouseup` events with `pointerdown`, `pointermove`, and `pointerup` to ensure smoother touch interactions on mobile.
- The new event handling allows for consistent behavior across both mouse and touch inputs, enhancing the overall user experience on mobile devices.
- Mobile devices often have issues with mouse events, especially when it comes to touch interactions, so using pointer events ensures better compatibility and responsiveness.
- This refactor ensures that the drag …

feat: replace mouse events with pointer events for toolbar drag and drop on mobile

---

LICENSE
packages/scan/src/web/utils/geiger.ts
packages/scan/tsup.config.ts
packages/vite-plugin-react-scan/LICENSE
packages/website/components/footer.tsx

This PR updates the year from 2024 to 2025 in the footer and other docs

fix: year updated to 2025

---

packages/scan/src/core/notifications/event-tracking.ts
packages/scan/src/core/notifications/performance.ts
packages/scan/src/web/views/notifications/data.ts
packages/scan/src/web/views/notifications/notifications.tsx
packages/scan/src/web/views/notifications/render-bar-chart.tsx

Recursively shows the parents (that rendered) of notification render bars
This is a little tricky to implement perfectly (w.r.t UX) since it's trivial to create a cycle:
```html
<Div>
<Button>
<Div>
<Button/>
</Div>
</Button>
</Div>
```
In this case Div is a parent of Button, and vice versa. So this tree would recurse forever in notifications. 
This a limit to how the fiber renders datastructure is aggregated. We group fibers that are created from the same component together, and just store the count. So we have no way to express how many layers this cyclical structure holds. We can only track that some Div's had a Button parent, and some Buttons had a Div parent
This actually is fine in most cases, and I could not think of a trivial way to represent this better, while allowing memory to …

feat: show rendered parents in notifications view

---

packages/scan/src/core/utils.ts

This fixes a bad logic in the `updateFiberRenderData` util.

fix: update fiber renderData for both function and object types

---

README.md
docs/installation/rsbuild.md

Added Rsbuild installation guide to help Rsbuild users use react-scan more easily.
Ref:
- Related issue: https://github.com/aidenybai/react-scan/issues/18
- Rsbuild is an Rspack-based build tool, see https://rsbuild.dev/

docs: add installation guide for Rsbuild

---

packages/scan/src/web/views/notifications/notification-header.tsx
packages/scan/src/web/views/notifications/slowdown-history.tsx
packages/scan/src/web/views/toolbar/index.tsx

Certain buttons that only has icons is missing the title attribute. This causes accessibility scanners, for instance Axe, to fail when having react-scan active on a webpage.
This title adds the missing attributes that I could identify. If there are more, I'm happy to fix those as well.

fix: add missing title attribute

---

packages/scan/src/core/instrumentation.ts
packages/scan/src/web/views/inspector/components-tree/index.tsx

fix https://github.com/aidenybai/react-scan/issues/356
I was waiting for feedback from the team, but I think it's better to open a PR so everyone can have a look into the proposed solution :) Suggestions are welcome!
**[Root cause]**
I believe this is due to [renderDataMap](https://github.com/aidenybai/react-scan/blob/main/packages/scan/src/core/instrumentation.ts#L441) using the fiber's `type` (function / class associated to the fiber) as the key.
In the example from the issue, it doesn't work because both the fibers share the same `type` reference. Since they share the same key in the `renderDataMap`, hence both have the same value (renderCount). 
This issue also happens without the keys:
```
<Toolbar toolbar={topToolbar} />
<Toolbar toolbar={bottomToolbar} />
```
**[Proposed …

fix: duplicate render count when one component is reused multiple times

---

packages/scan/src/web/views/inspector/overlay/index.tsx
packages/scan/src/web/widget/helpers.ts

fix https://github.com/aidenybai/react-scan/issues/358
**Changes**
-  override the calculations in the toolbar positioning and resizing if it is RTL (by checking the directionality set in the `documentElement`
**Examples**
https://github.com/user-attachments/assets/77eaa3c2-bb86-42f4-901d-af8adf59b43c

fix: RTL toolbar missing

---

packages/scan/src/core/instrumentation.ts
packages/scan/src/web/views/inspector/components-tree/index.tsx

fix https://github.com/aidenybai/react-scan/issues/355
`@emotion/styled` and `styled-components` [call components with forwardRef](https://github.com/emotion-js/emotion/blob/cce67ec6b2fc94261028b4f4778aae8c3d6c5fd6/packages/react/src/context.tsx#L30-L47) when generating them. We weren’t retrieving the fiber type from ForwardRef correctly, as it has a different data structure compared to functional and host components
To fix it, we just need to make a one line change: use `getRenderData(getType(node?.fiber))` instead of `getRenderData(node?.fiber.type)`.
Also, I cleaned up the code a bit as I just found out that Bippy already provides [getFiberId](https://github.com/aidenybai/bippy/blob/main/packages/bippy/src/core.ts#L555-L575) to manage uniqueId for fibers, so we don't really need to …

fix: compatible with styled components

---

packages/extension/src/utils/helpers.ts

The React detection logic was only checking for legacy root containers (`_reactRootContainer`) and missing container-based roots that use the `__reactContainer$` pattern. This caused React detection to fail in applications using container-based root structures.
- Added detection for container-based roots by checking for properties that start with `__reactContainer$`

fix: detect react root in extension

---

packages/scan/src/web/views/notifications/render-explanation.tsx

This typo appears in this component:

fix: Render explanation typo
